# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HyperSnapDemoApp_React' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for HyperSnapDemoApp_React

  pod 'HyperSnapSDK', :git => 'https://github.com/hyperverge/capture-ios-sdk.git', :tag => '2.4.1'

end


